### ISSUE TITLE
Old product names appearing - browser cacheing?

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/LocationTracking#17]
Often when testing this solution I find ID Entry names from previous tests appear unexpectedly.

I have a test setup that I'm done with. For sake of example l used a product type called `MyPredefBulk1` with identifier `blk1`. I run `./stop.sh`, `docker system prune -a -f`, delete the git clone of `LocationTracking` and restart the pi. `docker ps` and `docker images` both return a blank table. There is no trace of the location tracking solution left on the pi.

After reboot, I clone `LocationTracking` again, run `./setup.sh`, `docker compose build` and `./start.sh`. I log into <pi_IPv4>:8002 and create a new product type (with a unique name I haven't used before, say `prod1`) and add an identifier to it, also novel eg `p1`. I move one unit of this from one of the default locations to the other. The name shown in the dashboard is not `prod1` - the only product type in the database - but `MyPredefBulk1` which doesn't exist in this build.

Could these names be cached in the browser? Where else are they stored? I know there is an autoid underneath each name, to allow renaming and it's plausible that these product types are sharing an autoid. But why isn't the autoid to ID Entry name lookup table being replaced too?

![image](https://github.com/user-attachments/assets/1bb6c168-655e-4450-bb21-8b84a6e93f03)

**Comment by tobyaharris** [comment]
Closing the browser window and opening a new one resets the name to `loading...` momentarily before showing the correct name.  Suggests it is a browser session cache.

**Comment by Greg-Hawkridge** [comment]
![Image](https://github.com/user-attachments/assets/899b7d84-4c89-4040-85bf-4a0e81caa46c)

**Comment by tobyaharris** [comment]
Can be cleared from the browser - `localhost:8000/settings`
Add notes to instruction?

**Comment by tobyaharris** [comment]
Between these two factors:
- This is only reproduced when deleting identities, which users will not usually do ever (even if devs do).
- This can be remedied by simply closing and reopening the browser window
I propose this isn't worth any further effort now it is understood. The closed issue here serves as adequate documentation.
