### ISSUE TITLE
Is this repo active? How does it compare to Job Tracking?

### ISSUE THREAD

**Issue by tobyaharris** [DigitalShoestringSolutions/LocationTracking#4]
Our Job Tracking Starter Solution 
https://github.com/DigitalShoestringSolutions/JobTrackingStarterSolution
appears very similar to this, but is more active and used in a guide. 

What is the future of this repository?

**Comment by tobyaharris** [comment]
Manually adding to issue tracker

**Comment by Greg-Hawkridge** [comment]
It's the future of Job Tracking, it's deployed in some companies, but still needs some work before general use.
